### ISSUE TITLE
getting the following exception:

### ISSUE THREAD

**Issue by Florenz23** [breuerfelix/ineedfriends#4]
current progress: 6
skip media!
current progress: 7
interact with media
like media
comment liking currently not supported
generate new feed
(node:6577) UnhandledPromiseRejectionWarning: IgPrivateUserError: GET /api/v1/feed/user/4558395513/ - 400 Bad Request; Not authorized to view user
    at Request.handleResponseError (/Volumes/testing/insta/instabro2.0/ineedfriends/node_modules/instagram-private-api/src/core/request.ts:125:16)
    at Request.send (/Volumes/esting/insta/instabro2.0/ineedfriends/node_modules/instagram-private-api/src/core/request.ts:76:24)
(node:6577) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6577) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by breuerfelix** [comment]
i tried to get the feed of a private user -> fixed in next commit !
